### ISSUE TITLE
Map Design

### ISSUE THREAD

**Issue by rhruocco** [AlenLI232314/Table-Legend#6]

**Comment by VinylKnight** [comment]
![Board Game Layouts](https://user-images.githubusercontent.com/33336283/107815405-f7ec8080-6d38-11eb-9626-a139674892f0.png)
![Board Game Layouts3](https://user-images.githubusercontent.com/33336283/107815437-fc189e00-6d38-11eb-8fe1-e6c7e2ad27f6.png)
![Board Game Layouts2](https://user-images.githubusercontent.com/33336283/107815448-fd49cb00-6d38-11eb-9b2f-0392bd5e1e25.png)
